### ISSUE TITLE
Issue creation fails when project name and identifier do not match

### ISSUE THREAD

**Issue by mike-wendt** [mike-wendt/redmine-slackbot#4]
Project name is `Computers`
Project identifier is `comp`

Running this command:
```
@redminebot issuep comp Install SSL certs
```
Results in:
```
Traceback (most recent call last):
  File "redminebot.py", line 480, in rm_create_issue
    return rcn.issue.create(project_id=project, tracker_id=REDMINE_TRACKER_ID, **params)
  File "/opt/redminebot/env/local/lib/python2.7/site-packages/redminelib/managers.py", line 179, in create
    response = self.redmine.engine.request(self.resource_class.http_method_create, url, data=data)
  File "/opt/redminebot/env/local/lib/python2.7/site-packages/redminelib/engines/base.py", line 75, in request
    return self.process_response(self.session.request(method, url, **kwargs), return_raw)
  File "/opt/redminebot/env/local/lib/python2.7/site-packages/redminelib/engines/base.py", line 158, in process_response
    raise exceptions.ResourceNotFoundError
ResourceNotFoundError: Requested resource doesn't exist
Traceback (most recent call last):
  File "redminebot.py", line 268, in create_issue
    issue = rm_create_issue(estimate=estimate, subject=clean_text, rcn=rcn, assigned=assigned.id, project=project, version=None)
  File "redminebot.py", line 483, in rm_create_issue
    raise RuntimeError(":x: Issue creation failed")
RuntimeError: :x: Issue creation failed
```

**Comment by mike-wendt** [comment]
Found the issue `rm_get_project()` returns the correct project but in the process of creating the issue the project name of `Computers` is passed instead of the project ID or the identifier of `comp` which results in the logged error
